In [20]:
#import pysr
import pandas as pd
import os
from pysr import PySRRegressor,TensorBoardLoggerSpec
import sympy
import numpy as np
import itertools
import random
import ast
import re
import warnings
warnings.filterwarnings("ignore")

In [21]:
# create dataframes 
dir = "datasets/Feynman/Feynman_with_units"
df_dict={}
mean=0
gamma = 0.001
for file in os.listdir(dir):
    if file in ['I.15.10.txt', 'I.48.20.txt', 'II.11.7.txt']:
        continue # these dont have a corresponding entry in the metadata file for some reason...
    fname = os.fsdecode(file)
    df = pd.read_csv(os.path.join(dir,fname),sep=" ",header=None,engine='pyarrow') # switching engine to pyarrow sped up loading by nearly 6x
    # add noise to the target variable as described by the paper Symbolic Regression with a Learned Concept Library
    std = gamma*np.sqrt((1/df.shape[0])*np.sum((df.iloc[:,-1:])**2))
    noise_array = np.random.normal(mean, std, size=df.shape[0])
    df.iloc[:,-1] = df.iloc[:,-1] + noise_array
    dfname,_ = os.path.splitext(fname)
    df_dict[dfname] = df

print("DFs created")
file="best_equations.csv",  

c=0

DFs created

In [22]:
class ConvertMinus(ast.NodeTransformer):
    def visit_UnaryOp(self,node):
        self.generic_visit(node)
        if isinstance(node.op,ast.USub):
            return ast.BinOp(left=ast.Constant(value=0),op=ast.Sub(),right=node.operand)
    
        return node

In [23]:
from pydantic import BaseModel,Field,field_validator
import typing

class ResponseStructure(BaseModel):
    expressions:typing.List[str] = Field(...,min_length=1,max_length=3,description="A list of expressions generated by the model")
    
    @field_validator("expressions",mode='before')
    @classmethod
    def remove_equals(cls, v):
        if isinstance(v, list):
            cleaned_expressions = []
            for expr in v:
                if isinstance(expr, str) and '=' in expr:
                    clean_expr = expr.split('=', 1)[-1].strip()
                    cleaned_expressions.append(clean_expr)
                else:
                    cleaned_expressions.append(expr)
            return cleaned_expressions
        return v
        
    
    @field_validator("expressions")
    @classmethod
    def check_equations(cls,expr_list):
        clean_list=[]
        for expr in expr_list:
            if '**' in expr:
                raise ValueError("invalid julia syntax for ** in {expr}. Must use ^ ")
            test_expr = expr.replace("^", "**")
            try:
                tree=ast.parse(test_expr,mode='eval')
                tree=ConvertMinus().visit(tree)
                clean_expr = ast.unparse(tree).replace("**", "^")
                clean_list.append(clean_expr)
            except SyntaxError as e:
                raise ValueError(f"Syntax error in expression '{expr}': {e}")
        return clean_list
        
schema = ResponseStructure.model_json_schema()

In [24]:
df_meta = pd.read_csv('datasets/Feynman/FeynmanEquations.csv') # get the number of variables, the variable names 
df_units = pd.read_csv('datasets/Feynman/units.csv')
unit_map = df_units.set_index('Variable')['Units'].to_dict()

In [25]:
import openai
import typing
import json



def call_model(schema:dict[str,typing.Any],
              equations:pd.DataFrame,
              meta:pd.DataFrame,
              df_name:str,
              MAX_ATTEMPTS:int=20,
              MAX_REQ_EXPRS:int=3,
              error_info=None) -> typing.List[str]:   

    client = openai.OpenAI(
        base_url="https://eleanora-unaggravating-ochlocratically.ngrok-free.dev/v1", 
        api_key = "sk-no-key-required"
    )
    parsed=None
    out='{}'
    num_vars=meta.loc[meta['Filename'] == df_name, '# variables'].values[0]
    print(f"Number of variables: {num_vars}")
    variables= [meta.loc[meta['Filename'] == df_name,f'v{i+1}_name'].values[0] for i in range(int(num_vars))]
    target_variable=  meta.loc[meta['Filename']==df_name,'Output'].values[0]
    print(f"Variables: {variables}")    
    current_units = {v: unit_map.get(v) for v in variables}
    target_unit = unit_map.get(target_variable)
    
    print(f"{target_variable}:{target_unit}")
    print(f"Units: {current_units}")    
    
    mapping={var:f'x{i}' for i,var in enumerate(variables)}
    print(f"Mapping: {mapping}")
    
    allowed_vars_regex = "|".join(re.escape(v) for v in variables)
    regex_string = rf"^([0-9+*/^() .-]|{allowed_vars_regex}|sin|cos|exp|log|sqrt)+$"
    schema["properties"]["expressions"]["items"]["pattern"] = regex_string
    correct_expr_list=[]
    wrong_expr_list=[]
    attempts=0
    
    while len(correct_expr_list) < MAX_REQ_EXPRS: # either get 3 correct equations or no
        if attempts == MAX_ATTEMPTS:
            break  

        completion = client.chat.completions.create(
            model="local-model",
            messages=[
                {
                    "role": "system",
                    "content": f"""You are an expert at crafting physical expressions. 
                                CRITICAL CONSTRAINTS:
                                    1. If a mathematical constant is required, you MUST use its numerical value. 
                                        - BAD: m * c^2
                                        - GOOD: m * 299792458^2
                                        - BAD: 2 * pi * r
                                        - GOOD: 2 * 3.14159 * r
                                2. Output MUST be a valid JSON object strictly following this schema: {json.dumps(schema)}"""
                },
                {
                    "role": "user",
                    "content": f'''
                                {error_info if error_info is not None else " " }
                                Generate THREE expressions given the physical quantities listed below. 
                                The expressions MUST be valid Julia syntax.                                                               
                                number of variables: {int(num_vars)}
                                variables: {variables}
                                units: {current_units} 
                                target variable: {target_variable}
                                target_unit: {target_unit}                                                               
                                make sure to use ONLY the above mentioned variable names. Draw on your knowledge of physics
                                to generate physically meaningful candidate expressions.
                                
                                '''
                } 
            ],
            response_format={
                "type": "json_object",
                "schema":schema
            },
            temperature=0.3,
        )
# TODO: Try to not  add the hall of fame        
#TODO: in the final report, say something about whether or not the output was used, 
# TODO: how often it was syntactically correct, whether or not it copid the call of fame.

        try:
            out=completion.choices[0].message.content
            
            print(f"validating {out} ... ")
            parsed = ResponseStructure.model_validate_json(out)
            print("validated successfully")           
            
            for eq in parsed.expressions:
                if eq not in correct_expr_list:
                    correct_expr_list.append(eq)              
        except Exception as e:
            wrong_expr_list.append(out)       
            print(f"Validation failed with {e}. Retrying. Attempt# {attempts+1}")
            
        attempts+=1
    
    for i,expr in enumerate(correct_expr_list):            
        for var,n_var in mapping.items():
            pattern = r'\b' + re.escape(var) + r'\b'
            expr = re.sub(pattern, n_var, expr)
        correct_expr_list[i] = expr

        
    print("final expression list: ")
    print(correct_expr_list)
    return correct_expr_list

In [ ]:
def run_search(df_dict,fresh_start=False):
    MAX_CALLS=19
    MAX_FITTING_ERRORS=5
    c=0
    best_list=[]
    if fresh_start is False:
        # read the file where we have stopped. 
        if os.path.exists('current_run.txt'):
            with open ('current_run.txt','r') as f:
                already_read=set(f.read().splitlines())
            all_dfs = set(df_dict.keys())
            to_read=all_dfs-already_read
            # re-create df_dict so next code can be reused
            df_dict={fname:df_dict[fname] for fname in to_read}  
         
        else:                        
            print("current_run.txt does not exist. Reverting to fresh start.")
    
    for name,df in df_dict.items(): 
        if c==19:
            break            
        X=df.iloc[:10000,:-1]
        y=df.iloc[:10000,-1] 
        print(f"Going through DF {c+1} solving for equation {name}, X shape: {X.shape}, y shape: {y.shape}")
        logger_spec = TensorBoardLoggerSpec(
                        log_dir="logs/run",
                        log_interval=5,  # Log every 5 iterations
                        )   
        model=PySRRegressor(niterations=5, 
                            warm_start=True,
                            guesses=[],
                            batching=True,
                            batch_size=32,
                            verbosity=0,
                            # constraints={"sin": 10, "cos": 10,
                            #             "exp": 20, "log": 20, "sqrt": 20,
                            #             "pow": (-1, 20)},
                            nested_constraints={"sin": {"sin": 0, "cos": 0},
                                                "cos": {"sin": 0, "cos": 0},
                                                "exp": {"exp":0, "log": 0},
                                                "log": {"exp": 0, "log": 0},
                                                "sqrt": {"sqrt": 0}},
                            unary_operators=["sqrt","exp","sin","cos","log"],
                            binary_operators=["+", "*", "/", "^","-"],
                            fraction_replaced_guesses=0.01, # default is 0.001
                            logger_spec=logger_spec) # constraints taken from paper. 
        
        model.fit(X,y) 
        for _ in range (MAX_CALLS):
            if random.random()<0.1: # 10% of the time
                fitting_errors=0
                print(f"LLM called. Sending equations and meta info")
                print("Hall of Fame currently: ")
                print(model.equations_)

                llm_guesses= call_model(schema,model.equations_,df_meta,name)
                model.set_params(guesses=llm_guesses)
                while fitting_errors<MAX_FITTING_ERRORS:                    
                    try:   
                        model.fit(X,y)
                        break
                    except Exception as e: # just try again
                        fitting_errors+=1
                        e=str(e)
                        print(f"Exception encountered when fitting. Trying again. (Attempt: {fitting_errors})")
                        if 'Stacktrace' in e:
                            message,_ = e.split('Stacktrace:',1)    
                        else:
                            message=e   
                        message += f' The error is here: {llm_guesses}. Please re-generate the guesses after correction'   
                
                        llm_guesses = call_model(schema,model.equations_,df_meta,name,error_info=message)
                        model.set_params(guesses=llm_guesses)

                    # reset for the next iteration. 
                model.set_params(guesses=[])
            else:
                # continue as normal 
                model.fit(X,y)

        best=model.equations_.sort_values("score",axis=0,ascending=False).iloc[[0]].copy() # score chooses the equation with the best complexity-accuracy trade off.
        best["Filename"] = name 
        best.to_csv('best_eqs_20_guided.csv', mode='a', index=False, header=not os.path.exists('best_eqs_20_guided.csv'))
        best_list.append(best)
        # save the name of the df into a text file 
        with open ('current_run.txt','a') as f:
            f.write(f'{name}\n')
        c+=1
run_search(df_dict,fresh_start=True)

# 7.5 minutes to run without llm, got 8 correct

Going through DF 1 solving for equation III.15.27, X shape: (10000, 3), y shape: (10000,)
Going through DF 2 solving for equation III.4.33, X shape: (10000, 4), y shape: (10000,)
Going through DF 3 solving for equation I.24.6, X shape: (10000, 4), y shape: (10000,)
Going through DF 4 solving for equation III.9.52, X shape: (10000, 6), y shape: (10000,)
Going through DF 5 solving for equation I.34.14, X shape: (10000, 3), y shape: (10000,)
Going through DF 6 solving for equation III.7.38, X shape: (10000, 3), y shape: (10000,)
Going through DF 7 solving for equation II.15.4, X shape: (10000, 3), y shape: (10000,)
Going through DF 8 solving for equation I.41.16, X shape: (10000, 5), y shape: (10000,)
Going through DF 9 solving for equation I.18.12, X shape: (10000, 3), y shape: (10000,)
Going through DF 10 solving for equation II.11.3, X shape: (10000, 5), y shape: (10000,)
Going through DF 11 solving for equation II.21.32, X shape: (10000, 5), y shape: (10000,)
Going through DF 12 solving for equation II.6.15b, X shape: (10000, 4), y shape: (10000,)
Going through DF 13 solving for equation II.34.29b, X shape: (10000, 5), y shape: (10000,)
Going through DF 14 solving for equation I.14.3, X shape: (10000, 3), y shape: (10000,)
Going through DF 15 solving for equation I.13.12, X shape: (10000, 5), y shape: (10000,)
Going through DF 16 solving for equation I.10.7, X shape: (10000, 3), y shape: (10000,)
Going through DF 17 solving for equation I.12.5, X shape: (10000, 2), y shape: (10000,)
Going through DF 18 solving for equation I.43.16, X shape: (10000, 4), y shape: (10000,)
Going through DF 19 solving for equation II.15.5, X shape: (10000, 3), y shape: (10000,)

In [38]:
symbols = sympy.symbols("""
sigma theta1 x1 x2 y1 y2 m1 m2 G z1
z2 m_0 v c x3 y3 mu Nn q1 q2
epsilon r Ef q B m u w r1 r2
z k_spring x t F omega omega_0 n theta2 d1
d2 Int_0 lambd d a p h I1 I2 delta
pr gamma kb n_0 mu_drift Volt mob V1 V2 rho
alpha kappa T1 T2 Pwr p_d y sigma_den chi n_rho
I rho_c_0 mom g_ Jz E_n Bx By Bz k
I_0 beta A_vec x0 x4 x5 x6 x7 x8 x9
""")
(sigma, theta1, x1, x2, y1, y2, m1, m2, G, z1,
z2, m_0, v, c, x3, y3, mu, Nn, q1, q2,
epsilon, r, Ef, q, B, m, u, w, r1, r2,
z, k_spring, x, t, F, omega, omega_0, n, theta2, d1,
d2, Int_0, lambd, d, a, p, h, I1, I2, delta,
pr, gamma, kb, n_0, mu_drift, Volt, mob, V1, V2, rho,
alpha, kappa, T1, T2, Pwr, p_d, y, sigma_den, chi, n_rho,
I, rho_c_0, mom, g_, Jz, E_n, Bx, By, Bz, k,
I_0, beta, A_vec,x0,x4,x5,x6,x7,x8,x9) = symbols

locals_ = {s.name: s for s in symbols}

In [40]:
# creating the core DF 

df_pred=pd.read_csv("best_eqs_20_unguided.csv")
df_original = pd.read_csv("datasets/Feynman/FeynmanEquations.csv")[["Filename","Formula"]]
df_merged = df_pred.merge(df_original,on="Filename",how='left')
df_merged["Equation"] = df_merged["Formula"].map(lambda f: sympy.sympify(f, locals=locals_))
df_merged["Predicted Equation"] = df_merged["sympy_format"].map(lambda f: sympy.sympify(f, locals=locals_))
df_merged= df_merged[["Filename","Equation","loss","Predicted Equation"]]
df_merged=df_merged.drop_duplicates(subset='Filename').set_index('Filename')
df_merged.drop(df_merged[df_merged['Equation']==sympy.nan].index,inplace=True)

In [41]:
# i want to know how similar these are...
# constants are an issue.. we will try to prove equivalence up to a constant 
pred_eqs = df_merged['Predicted Equation']
orig_eqs = df_merged['Equation']

In [30]:
def check_equality(pred_expr, true_expr, true_varnames=None):
    '''
    used to check if two sympy expressions are "equal".
    equality is defined here as equal upto a constant.
    Works by sampling the true equation and then trying out permutations 
    of the input variables of the candidate solution and obtaining the ratio of the fits. 
    If the ratios are identical, the expressions are equivalent upto a constant.  
    
    '''
    # print("Free symbols in the true expression: ")
    # print(true_expr.free_symbols)
    pred_vars = sorted(pred_expr.free_symbols, key=lambda s: s.name)
    if true_varnames:
        true_vars = [sympy.Symbol(n) for n in true_varnames]
    else:
        true_vars = sorted(true_expr.free_symbols, key=lambda s: s.name)
    # print("variables in the true expression: ")
    print(true_vars)
    if len(pred_vars) != len(true_vars):
        return False
# lambdify
    f_pred = sympy.lambdify(pred_vars, pred_expr, "numpy")
    f_true = sympy.lambdify(true_vars, true_expr, "numpy")
    
# 10 points 
    N_samples = 10
    X = np.random.uniform(1.0, 5.0, (N_samples, len(true_vars)))
    
    # Calculate True Output
    try:
        y_true = f_true(*X.T) # evaluate true function over 10 points. 
    except Exception:
        return False 

    best_perm = None
    
    for perm_indices in itertools.permutations(range(len(true_vars))): # [0,1,2] eg if len is 3
        print(perm_indices) # [0,1,2], [0,2,1]
        try:
            # Reorder columns of X to match this permutation
            X_permuted = X[:, perm_indices]
            
            # Eval prediction
            y_pred = f_pred(*X_permuted.T) # get the fit on y after re-ordering. 
            
            # Calculate Ratio: y_pred / y_true
            # If equations are equivalent (up to constant), ratio should be identical for all points
            ratio = y_pred / y_true            
            # Check if ratio is constant (sigma is almost 0)
            if np.std(ratio) < 1e-5 and np.isfinite(ratio).all():
                # We found a candidate permutation! 
                # Map the indices back to symbols
                best_perm = [true_vars[i] for i in perm_indices]
                break
                
        except Exception:
            continue

    if best_perm:
        mapper = dict(zip(pred_vars, best_perm)) # make the correct mapping.
        pred_mapped = pred_expr.subs(mapper)
        
        # run simplify for a final sanity check 
        final_ratio = sympy.simplify(pred_mapped / true_expr)
        
        if final_ratio.is_constant():
            return True

    return False

In [42]:
# finally, apply the above onto the dataframe and add the col
df_merged["equivalent"] = df_merged.apply(
    lambda row: check_equality(
        row["Predicted Equation"],   # predicted
        row["Equation"]        # ground truth
    ),
    axis=1
)

[alpha, d, n]
(0, 1, 2)
[T, h, kb, omega]
[m, omega, omega_0, x]
(0, 1, 2, 3)
(0, 1, 3, 2)
(0, 2, 1, 3)
(0, 2, 3, 1)
(0, 3, 1, 2)
(0, 3, 2, 1)
(1, 0, 2, 3)
(1, 0, 3, 2)
(1, 2, 0, 3)
(1, 2, 3, 0)
(1, 3, 0, 2)
(1, 3, 2, 0)
(2, 0, 1, 3)
(2, 0, 3, 1)
(2, 1, 0, 3)
(2, 1, 3, 0)
(2, 3, 0, 1)
(2, 3, 1, 0)
(3, 0, 1, 2)
(3, 0, 2, 1)
(3, 1, 0, 2)
(3, 1, 2, 0)
(3, 2, 0, 1)
(3, 2, 1, 0)
[Ef, h, omega, omega_0, p_d, t]
(0, 1, 2, 3, 4, 5)
(0, 1, 2, 3, 5, 4)
(0, 1, 2, 4, 3, 5)
(0, 1, 2, 4, 5, 3)
(0, 1, 2, 5, 3, 4)
(0, 1, 2, 5, 4, 3)
(0, 1, 3, 2, 4, 5)
(0, 1, 3, 2, 5, 4)
(0, 1, 3, 4, 2, 5)
(0, 1, 3, 4, 5, 2)
(0, 1, 3, 5, 2, 4)
(0, 1, 3, 5, 4, 2)
(0, 1, 4, 2, 3, 5)
(0, 1, 4, 2, 5, 3)
(0, 1, 4, 3, 2, 5)
(0, 1, 4, 3, 5, 2)
(0, 1, 4, 5, 2, 3)
(0, 1, 4, 5, 3, 2)
(0, 1, 5, 2, 3, 4)
(0, 1, 5, 2, 4, 3)
(0, 1, 5, 3, 2, 4)
(0, 1, 5, 3, 4, 2)
(0, 1, 5, 4, 2, 3)
(0, 1, 5, 4, 3, 2)
(0, 2, 1, 3, 4, 5)
(0, 2, 1, 3, 5, 4)
(0, 2, 1, 4, 3, 5)
(0, 2, 1, 4, 5, 3)
(0, 2, 1, 5, 3, 4)
(0, 2, 1, 5, 4, 3)
(0, 2, 3, 1, 4, 5)
(0, 2, 3, 1, 5, 4)
(0, 2, 3, 4, 1, 5)
(0, 2, 3, 4, 5, 1)
(0, 2, 3, 5, 1, 4)
(0, 2, 3, 5, 4, 1)
(0, 2, 4, 1, 3, 5)
(0, 2, 4, 1, 5, 3)
(0, 2, 4, 3, 1, 5)
(0, 2, 4, 3, 5, 1)
(0, 2, 4, 5, 1, 3)
(0, 2, 4, 5, 3, 1)
(0, 2, 5, 1, 3, 4)
(0, 2, 5, 1, 4, 3)
(0, 2, 5, 3, 1, 4)
(0, 2, 5, 3, 4, 1)
(0, 2, 5, 4, 1, 3)
(0, 2, 5, 4, 3, 1)
(0, 3, 1, 2, 4, 5)
(0, 3, 1, 2, 5, 4)
(0, 3, 1, 4, 2, 5)
(0, 3, 1, 4, 5, 2)
(0, 3, 1, 5, 2, 4)
(0, 3, 1, 5, 4, 2)
(0, 3, 2, 1, 4, 5)
(0, 3, 2, 1, 5, 4)
(0, 3, 2, 4, 1, 5)
(0, 3, 2, 4, 5, 1)
(0, 3, 2, 5, 1, 4)
(0, 3, 2, 5, 4, 1)
(0, 3, 4, 1, 2, 5)
(0, 3, 4, 1, 5, 2)
(0, 3, 4, 2, 1, 5)
(0, 3, 4, 2, 5, 1)
(0, 3, 4, 5, 1, 2)
(0, 3, 4, 5, 2, 1)
(0, 3, 5, 1, 2, 4)
(0, 3, 5, 1, 4, 2)
(0, 3, 5, 2, 1, 4)
(0, 3, 5, 2, 4, 1)
(0, 3, 5, 4, 1, 2)
(0, 3, 5, 4, 2, 1)
(0, 4, 1, 2, 3, 5)
(0, 4, 1, 2, 5, 3)
(0, 4, 1, 3, 2, 5)
(0, 4, 1, 3, 5, 2)
(0, 4, 1, 5, 2, 3)
(0, 4, 1, 5, 3, 2)
(0, 4, 2, 1, 3, 5)
(0, 4, 2, 1, 5, 3)
(0, 4, 2, 3, 1, 5)
(0, 4, 2, 3, 5, 1)
(0, 4, 2, 5, 1, 3)
(0, 4, 2, 5, 3, 1)
(0, 4, 3, 1, 2, 5)
(0, 4, 3, 1, 5, 2)
(0, 4, 3, 2, 1, 5)
(0, 4, 3, 2, 5, 1)
(0, 4, 3, 5, 1, 2)
(0, 4, 3, 5, 2, 1)
(0, 4, 5, 1, 2, 3)
(0, 4, 5, 1, 3, 2)
(0, 4, 5, 2, 1, 3)
(0, 4, 5, 2, 3, 1)
(0, 4, 5, 3, 1, 2)
(0, 4, 5, 3, 2, 1)
(0, 5, 1, 2, 3, 4)
(0, 5, 1, 2, 4, 3)
(0, 5, 1, 3, 2, 4)
(0, 5, 1, 3, 4, 2)
(0, 5, 1, 4, 2, 3)
(0, 5, 1, 4, 3, 2)
(0, 5, 2, 1, 3, 4)
(0, 5, 2, 1, 4, 3)
(0, 5, 2, 3, 1, 4)
(0, 5, 2, 3, 4, 1)
(0, 5, 2, 4, 1, 3)
(0, 5, 2, 4, 3, 1)
(0, 5, 3, 1, 2, 4)
(0, 5, 3, 1, 4, 2)
(0, 5, 3, 2, 1, 4)
(0, 5, 3, 2, 4, 1)
(0, 5, 3, 4, 1, 2)
(0, 5, 3, 4, 2, 1)
(0, 5, 4, 1, 2, 3)
(0, 5, 4, 1, 3, 2)
(0, 5, 4, 2, 1, 3)
(0, 5, 4, 2, 3, 1)
(0, 5, 4, 3, 1, 2)
(0, 5, 4, 3, 2, 1)
(1, 0, 2, 3, 4, 5)
(1, 0, 2, 3, 5, 4)
(1, 0, 2, 4, 3, 5)
(1, 0, 2, 4, 5, 3)
(1, 0, 2, 5, 3, 4)
(1, 0, 2, 5, 4, 3)
(1, 0, 3, 2, 4, 5)
(1, 0, 3, 2, 5, 4)
(1, 0, 3, 4, 2, 5)
(1, 0, 3, 4, 5, 2)
(1, 0, 3, 5, 2, 4)
(1, 0, 3, 5, 4, 2)
(1, 0, 4, 2, 3, 5)
(1, 0, 4, 2, 5, 3)
(1, 0, 4, 3, 2, 5)
(1, 0, 4, 3, 5, 2)
(1, 0, 4, 5, 2, 3)
(1, 0, 4, 5, 3, 2)
(1, 0, 5, 2, 3, 4)
(1, 0, 5, 2, 4, 3)
(1, 0, 5, 3, 2, 4)
(1, 0, 5, 3, 4, 2)
(1, 0, 5, 4, 2, 3)
(1, 0, 5, 4, 3, 2)
(1, 2, 0, 3, 4, 5)
(1, 2, 0, 3, 5, 4)
(1, 2, 0, 4, 3, 5)
(1, 2, 0, 4, 5, 3)
(1, 2, 0, 5, 3, 4)
(1, 2, 0, 5, 4, 3)
(1, 2, 3, 0, 4, 5)
(1, 2, 3, 0, 5, 4)
(1, 2, 3, 4, 0, 5)
(1, 2, 3, 4, 5, 0)
(1, 2, 3, 5, 0, 4)
(1, 2, 3, 5, 4, 0)
(1, 2, 4, 0, 3, 5)
(1, 2, 4, 0, 5, 3)
(1, 2, 4, 3, 0, 5)
(1, 2, 4, 3, 5, 0)
(1, 2, 4, 5, 0, 3)
(1, 2, 4, 5, 3, 0)
(1, 2, 5, 0, 3, 4)
(1, 2, 5, 0, 4, 3)
(1, 2, 5, 3, 0, 4)
(1, 2, 5, 3, 4, 0)
(1, 2, 5, 4, 0, 3)
(1, 2, 5, 4, 3, 0)
(1, 3, 0, 2, 4, 5)
(1, 3, 0, 2, 5, 4)
(1, 3, 0, 4, 2, 5)
(1, 3, 0, 4, 5, 2)
(1, 3, 0, 5, 2, 4)
(1, 3, 0, 5, 4, 2)
(1, 3, 2, 0, 4, 5)
(1, 3, 2, 0, 5, 4)
(1, 3, 2, 4, 0, 5)
(1, 3, 2, 4, 5, 0)
(1, 3, 2, 5, 0, 4)
(1, 3, 2, 5, 4, 0)
(1, 3, 4, 0, 2, 5)
(1, 3, 4, 0, 5, 2)
(1, 3, 4, 2, 0, 5)
(1, 3, 4, 2, 5, 0)
(1, 3, 4, 5, 0, 2)
(1, 3, 4, 5, 2, 0)
(1, 3, 5, 0, 2, 4)
(1, 3, 5, 0, 4, 2)
(1, 3, 5, 2, 0, 4)
(1, 3, 5, 2, 4, 0)
(1, 3, 5, 4, 0, 2)
(1, 3, 5, 4, 2, 0)
(1, 4, 0, 2, 3, 5)
(1, 4, 0, 2, 5, 3)
(1, 4, 0, 3, 2, 5)
(1, 4, 0, 3, 5, 2)
(1, 4, 0, 5, 2, 3)
(1, 4, 0, 5, 3, 2)
(1, 4, 2, 0, 3, 5)
(1, 4, 2, 0, 5, 3)
(1, 4, 2, 3, 0, 5)
(1, 4, 2, 3, 5, 0)
(1, 4, 2, 5, 0, 3)
(1, 4, 2, 5, 3, 0)
(1, 4, 3, 0, 2, 5)
(1, 4, 3, 0, 5, 2)
(1, 4, 3, 2, 0, 5)
(1, 4, 3, 2, 5, 0)
(1, 4, 3, 5, 0, 2)
(1, 4, 3, 5, 2, 0)
(1, 4, 5, 0, 2, 3)
(1, 4, 5, 0, 3, 2)
(1, 4, 5, 2, 0, 3)
(1, 4, 5, 2, 3, 0)
(1, 4, 5, 3, 0, 2)
(1, 4, 5, 3, 2, 0)
(1, 5, 0, 2, 3, 4)
(1, 5, 0, 2, 4, 3)
(1, 5, 0, 3, 2, 4)
(1, 5, 0, 3, 4, 2)
(1, 5, 0, 4, 2, 3)
(1, 5, 0, 4, 3, 2)
(1, 5, 2, 0, 3, 4)
(1, 5, 2, 0, 4, 3)
(1, 5, 2, 3, 0, 4)
(1, 5, 2, 3, 4, 0)
(1, 5, 2, 4, 0, 3)
(1, 5, 2, 4, 3, 0)
(1, 5, 3, 0, 2, 4)
(1, 5, 3, 0, 4, 2)
(1, 5, 3, 2, 0, 4)
(1, 5, 3, 2, 4, 0)
(1, 5, 3, 4, 0, 2)
(1, 5, 3, 4, 2, 0)
(1, 5, 4, 0, 2, 3)
(1, 5, 4, 0, 3, 2)
(1, 5, 4, 2, 0, 3)
(1, 5, 4, 2, 3, 0)
(1, 5, 4, 3, 0, 2)
(1, 5, 4, 3, 2, 0)
(2, 0, 1, 3, 4, 5)
(2, 0, 1, 3, 5, 4)
(2, 0, 1, 4, 3, 5)
(2, 0, 1, 4, 5, 3)
(2, 0, 1, 5, 3, 4)
(2, 0, 1, 5, 4, 3)
(2, 0, 3, 1, 4, 5)
(2, 0, 3, 1, 5, 4)
(2, 0, 3, 4, 1, 5)
(2, 0, 3, 4, 5, 1)
(2, 0, 3, 5, 1, 4)
(2, 0, 3, 5, 4, 1)
(2, 0, 4, 1, 3, 5)
(2, 0, 4, 1, 5, 3)
(2, 0, 4, 3, 1, 5)
(2, 0, 4, 3, 5, 1)
(2, 0, 4, 5, 1, 3)
(2, 0, 4, 5, 3, 1)
(2, 0, 5, 1, 3, 4)
(2, 0, 5, 1, 4, 3)
(2, 0, 5, 3, 1, 4)
(2, 0, 5, 3, 4, 1)
(2, 0, 5, 4, 1, 3)
(2, 0, 5, 4, 3, 1)
(2, 1, 0, 3, 4, 5)
(2, 1, 0, 3, 5, 4)
(2, 1, 0, 4, 3, 5)
(2, 1, 0, 4, 5, 3)
(2, 1, 0, 5, 3, 4)
(2, 1, 0, 5, 4, 3)
(2, 1, 3, 0, 4, 5)
(2, 1, 3, 0, 5, 4)
(2, 1, 3, 4, 0, 5)
(2, 1, 3, 4, 5, 0)
(2, 1, 3, 5, 0, 4)
(2, 1, 3, 5, 4, 0)
(2, 1, 4, 0, 3, 5)
(2, 1, 4, 0, 5, 3)
(2, 1, 4, 3, 0, 5)
(2, 1, 4, 3, 5, 0)
(2, 1, 4, 5, 0, 3)
(2, 1, 4, 5, 3, 0)
(2, 1, 5, 0, 3, 4)
(2, 1, 5, 0, 4, 3)
(2, 1, 5, 3, 0, 4)
(2, 1, 5, 3, 4, 0)
(2, 1, 5, 4, 0, 3)
(2, 1, 5, 4, 3, 0)
(2, 3, 0, 1, 4, 5)
(2, 3, 0, 1, 5, 4)
(2, 3, 0, 4, 1, 5)
(2, 3, 0, 4, 5, 1)
(2, 3, 0, 5, 1, 4)
(2, 3, 0, 5, 4, 1)
(2, 3, 1, 0, 4, 5)
(2, 3, 1, 0, 5, 4)
(2, 3, 1, 4, 0, 5)
(2, 3, 1, 4, 5, 0)
(2, 3, 1, 5, 0, 4)
(2, 3, 1, 5, 4, 0)
(2, 3, 4, 0, 1, 5)
(2, 3, 4, 0, 5, 1)
(2, 3, 4, 1, 0, 5)
(2, 3, 4, 1, 5, 0)
(2, 3, 4, 5, 0, 1)
(2, 3, 4, 5, 1, 0)
(2, 3, 5, 0, 1, 4)
(2, 3, 5, 0, 4, 1)
(2, 3, 5, 1, 0, 4)
(2, 3, 5, 1, 4, 0)
(2, 3, 5, 4, 0, 1)
(2, 3, 5, 4, 1, 0)
(2, 4, 0, 1, 3, 5)
(2, 4, 0, 1, 5, 3)
(2, 4, 0, 3, 1, 5)
(2, 4, 0, 3, 5, 1)
(2, 4, 0, 5, 1, 3)
(2, 4, 0, 5, 3, 1)
(2, 4, 1, 0, 3, 5)
(2, 4, 1, 0, 5, 3)
(2, 4, 1, 3, 0, 5)
(2, 4, 1, 3, 5, 0)
(2, 4, 1, 5, 0, 3)
(2, 4, 1, 5, 3, 0)
(2, 4, 3, 0, 1, 5)
(2, 4, 3, 0, 5, 1)
(2, 4, 3, 1, 0, 5)
(2, 4, 3, 1, 5, 0)
(2, 4, 3, 5, 0, 1)
(2, 4, 3, 5, 1, 0)
(2, 4, 5, 0, 1, 3)
(2, 4, 5, 0, 3, 1)
(2, 4, 5, 1, 0, 3)
(2, 4, 5, 1, 3, 0)
(2, 4, 5, 3, 0, 1)
(2, 4, 5, 3, 1, 0)
(2, 5, 0, 1, 3, 4)
(2, 5, 0, 1, 4, 3)
(2, 5, 0, 3, 1, 4)
(2, 5, 0, 3, 4, 1)
(2, 5, 0, 4, 1, 3)
(2, 5, 0, 4, 3, 1)
(2, 5, 1, 0, 3, 4)
(2, 5, 1, 0, 4, 3)
(2, 5, 1, 3, 0, 4)
(2, 5, 1, 3, 4, 0)
(2, 5, 1, 4, 0, 3)
(2, 5, 1, 4, 3, 0)
(2, 5, 3, 0, 1, 4)
(2, 5, 3, 0, 4, 1)
(2, 5, 3, 1, 0, 4)
(2, 5, 3, 1, 4, 0)
(2, 5, 3, 4, 0, 1)
(2, 5, 3, 4, 1, 0)
(2, 5, 4, 0, 1, 3)
(2, 5, 4, 0, 3, 1)
(2, 5, 4, 1, 0, 3)
(2, 5, 4, 1, 3, 0)
(2, 5, 4, 3, 0, 1)
(2, 5, 4, 3, 1, 0)
(3, 0, 1, 2, 4, 5)
(3, 0, 1, 2, 5, 4)
(3, 0, 1, 4, 2, 5)
(3, 0, 1, 4, 5, 2)
(3, 0, 1, 5, 2, 4)
(3, 0, 1, 5, 4, 2)
(3, 0, 2, 1, 4, 5)
(3, 0, 2, 1, 5, 4)
(3, 0, 2, 4, 1, 5)
(3, 0, 2, 4, 5, 1)
(3, 0, 2, 5, 1, 4)
(3, 0, 2, 5, 4, 1)
(3, 0, 4, 1, 2, 5)
(3, 0, 4, 1, 5, 2)
(3, 0, 4, 2, 1, 5)
(3, 0, 4, 2, 5, 1)
(3, 0, 4, 5, 1, 2)
(3, 0, 4, 5, 2, 1)
(3, 0, 5, 1, 2, 4)
(3, 0, 5, 1, 4, 2)
(3, 0, 5, 2, 1, 4)
(3, 0, 5, 2, 4, 1)
(3, 0, 5, 4, 1, 2)
(3, 0, 5, 4, 2, 1)
(3, 1, 0, 2, 4, 5)
(3, 1, 0, 2, 5, 4)
(3, 1, 0, 4, 2, 5)
(3, 1, 0, 4, 5, 2)
(3, 1, 0, 5, 2, 4)
(3, 1, 0, 5, 4, 2)
(3, 1, 2, 0, 4, 5)
(3, 1, 2, 0, 5, 4)
(3, 1, 2, 4, 0, 5)
(3, 1, 2, 4, 5, 0)
(3, 1, 2, 5, 0, 4)
(3, 1, 2, 5, 4, 0)
(3, 1, 4, 0, 2, 5)
(3, 1, 4, 0, 5, 2)
(3, 1, 4, 2, 0, 5)
(3, 1, 4, 2, 5, 0)
(3, 1, 4, 5, 0, 2)
(3, 1, 4, 5, 2, 0)
(3, 1, 5, 0, 2, 4)
(3, 1, 5, 0, 4, 2)
(3, 1, 5, 2, 0, 4)
(3, 1, 5, 2, 4, 0)
(3, 1, 5, 4, 0, 2)
(3, 1, 5, 4, 2, 0)
(3, 2, 0, 1, 4, 5)
(3, 2, 0, 1, 5, 4)
(3, 2, 0, 4, 1, 5)
(3, 2, 0, 4, 5, 1)
(3, 2, 0, 5, 1, 4)
(3, 2, 0, 5, 4, 1)
(3, 2, 1, 0, 4, 5)
(3, 2, 1, 0, 5, 4)
(3, 2, 1, 4, 0, 5)
(3, 2, 1, 4, 5, 0)
(3, 2, 1, 5, 0, 4)
(3, 2, 1, 5, 4, 0)
(3, 2, 4, 0, 1, 5)
(3, 2, 4, 0, 5, 1)
(3, 2, 4, 1, 0, 5)
(3, 2, 4, 1, 5, 0)
(3, 2, 4, 5, 0, 1)
(3, 2, 4, 5, 1, 0)
(3, 2, 5, 0, 1, 4)
(3, 2, 5, 0, 4, 1)
(3, 2, 5, 1, 0, 4)
(3, 2, 5, 1, 4, 0)
(3, 2, 5, 4, 0, 1)
(3, 2, 5, 4, 1, 0)
(3, 4, 0, 1, 2, 5)
(3, 4, 0, 1, 5, 2)
(3, 4, 0, 2, 1, 5)
(3, 4, 0, 2, 5, 1)
(3, 4, 0, 5, 1, 2)
(3, 4, 0, 5, 2, 1)
(3, 4, 1, 0, 2, 5)
(3, 4, 1, 0, 5, 2)
(3, 4, 1, 2, 0, 5)
(3, 4, 1, 2, 5, 0)
(3, 4, 1, 5, 0, 2)
(3, 4, 1, 5, 2, 0)
(3, 4, 2, 0, 1, 5)
(3, 4, 2, 0, 5, 1)
(3, 4, 2, 1, 0, 5)
(3, 4, 2, 1, 5, 0)
(3, 4, 2, 5, 0, 1)
(3, 4, 2, 5, 1, 0)
(3, 4, 5, 0, 1, 2)
(3, 4, 5, 0, 2, 1)
(3, 4, 5, 1, 0, 2)
(3, 4, 5, 1, 2, 0)
(3, 4, 5, 2, 0, 1)
(3, 4, 5, 2, 1, 0)
(3, 5, 0, 1, 2, 4)
(3, 5, 0, 1, 4, 2)
(3, 5, 0, 2, 1, 4)
(3, 5, 0, 2, 4, 1)
(3, 5, 0, 4, 1, 2)
(3, 5, 0, 4, 2, 1)
(3, 5, 1, 0, 2, 4)
(3, 5, 1, 0, 4, 2)
(3, 5, 1, 2, 0, 4)
(3, 5, 1, 2, 4, 0)
(3, 5, 1, 4, 0, 2)
(3, 5, 1, 4, 2, 0)
(3, 5, 2, 0, 1, 4)
(3, 5, 2, 0, 4, 1)
(3, 5, 2, 1, 0, 4)
(3, 5, 2, 1, 4, 0)
(3, 5, 2, 4, 0, 1)
(3, 5, 2, 4, 1, 0)
(3, 5, 4, 0, 1, 2)
(3, 5, 4, 0, 2, 1)
(3, 5, 4, 1, 0, 2)
(3, 5, 4, 1, 2, 0)
(3, 5, 4, 2, 0, 1)
(3, 5, 4, 2, 1, 0)
(4, 0, 1, 2, 3, 5)
(4, 0, 1, 2, 5, 3)
(4, 0, 1, 3, 2, 5)
(4, 0, 1, 3, 5, 2)
(4, 0, 1, 5, 2, 3)
(4, 0, 1, 5, 3, 2)
(4, 0, 2, 1, 3, 5)
(4, 0, 2, 1, 5, 3)
(4, 0, 2, 3, 1, 5)
(4, 0, 2, 3, 5, 1)
(4, 0, 2, 5, 1, 3)
(4, 0, 2, 5, 3, 1)
(4, 0, 3, 1, 2, 5)
(4, 0, 3, 1, 5, 2)
(4, 0, 3, 2, 1, 5)
(4, 0, 3, 2, 5, 1)
(4, 0, 3, 5, 1, 2)
(4, 0, 3, 5, 2, 1)
(4, 0, 5, 1, 2, 3)
(4, 0, 5, 1, 3, 2)
(4, 0, 5, 2, 1, 3)
(4, 0, 5, 2, 3, 1)
(4, 0, 5, 3, 1, 2)
(4, 0, 5, 3, 2, 1)
(4, 1, 0, 2, 3, 5)
(4, 1, 0, 2, 5, 3)
(4, 1, 0, 3, 2, 5)
(4, 1, 0, 3, 5, 2)
(4, 1, 0, 5, 2, 3)
(4, 1, 0, 5, 3, 2)
(4, 1, 2, 0, 3, 5)
(4, 1, 2, 0, 5, 3)
(4, 1, 2, 3, 0, 5)
(4, 1, 2, 3, 5, 0)
(4, 1, 2, 5, 0, 3)
(4, 1, 2, 5, 3, 0)
(4, 1, 3, 0, 2, 5)
(4, 1, 3, 0, 5, 2)
(4, 1, 3, 2, 0, 5)
(4, 1, 3, 2, 5, 0)
(4, 1, 3, 5, 0, 2)
(4, 1, 3, 5, 2, 0)
(4, 1, 5, 0, 2, 3)
(4, 1, 5, 0, 3, 2)
(4, 1, 5, 2, 0, 3)
(4, 1, 5, 2, 3, 0)
(4, 1, 5, 3, 0, 2)
(4, 1, 5, 3, 2, 0)
(4, 2, 0, 1, 3, 5)
(4, 2, 0, 1, 5, 3)
(4, 2, 0, 3, 1, 5)
(4, 2, 0, 3, 5, 1)
(4, 2, 0, 5, 1, 3)
(4, 2, 0, 5, 3, 1)
(4, 2, 1, 0, 3, 5)
(4, 2, 1, 0, 5, 3)
(4, 2, 1, 3, 0, 5)
(4, 2, 1, 3, 5, 0)
(4, 2, 1, 5, 0, 3)
(4, 2, 1, 5, 3, 0)
(4, 2, 3, 0, 1, 5)
(4, 2, 3, 0, 5, 1)
(4, 2, 3, 1, 0, 5)
(4, 2, 3, 1, 5, 0)
(4, 2, 3, 5, 0, 1)
(4, 2, 3, 5, 1, 0)
(4, 2, 5, 0, 1, 3)
(4, 2, 5, 0, 3, 1)
(4, 2, 5, 1, 0, 3)
(4, 2, 5, 1, 3, 0)
(4, 2, 5, 3, 0, 1)
(4, 2, 5, 3, 1, 0)
(4, 3, 0, 1, 2, 5)
(4, 3, 0, 1, 5, 2)
(4, 3, 0, 2, 1, 5)
(4, 3, 0, 2, 5, 1)
(4, 3, 0, 5, 1, 2)
(4, 3, 0, 5, 2, 1)
(4, 3, 1, 0, 2, 5)
(4, 3, 1, 0, 5, 2)
(4, 3, 1, 2, 0, 5)
(4, 3, 1, 2, 5, 0)
(4, 3, 1, 5, 0, 2)
(4, 3, 1, 5, 2, 0)
(4, 3, 2, 0, 1, 5)
(4, 3, 2, 0, 5, 1)
(4, 3, 2, 1, 0, 5)
(4, 3, 2, 1, 5, 0)
(4, 3, 2, 5, 0, 1)
(4, 3, 2, 5, 1, 0)
(4, 3, 5, 0, 1, 2)
(4, 3, 5, 0, 2, 1)
(4, 3, 5, 1, 0, 2)
(4, 3, 5, 1, 2, 0)
(4, 3, 5, 2, 0, 1)
(4, 3, 5, 2, 1, 0)
(4, 5, 0, 1, 2, 3)
(4, 5, 0, 1, 3, 2)
(4, 5, 0, 2, 1, 3)
(4, 5, 0, 2, 3, 1)
(4, 5, 0, 3, 1, 2)
(4, 5, 0, 3, 2, 1)
(4, 5, 1, 0, 2, 3)
(4, 5, 1, 0, 3, 2)
(4, 5, 1, 2, 0, 3)
(4, 5, 1, 2, 3, 0)
(4, 5, 1, 3, 0, 2)
(4, 5, 1, 3, 2, 0)
(4, 5, 2, 0, 1, 3)
(4, 5, 2, 0, 3, 1)
(4, 5, 2, 1, 0, 3)
(4, 5, 2, 1, 3, 0)
(4, 5, 2, 3, 0, 1)
(4, 5, 2, 3, 1, 0)
(4, 5, 3, 0, 1, 2)
(4, 5, 3, 0, 2, 1)
(4, 5, 3, 1, 0, 2)
(4, 5, 3, 1, 2, 0)
(4, 5, 3, 2, 0, 1)
(4, 5, 3, 2, 1, 0)
(5, 0, 1, 2, 3, 4)
(5, 0, 1, 2, 4, 3)
(5, 0, 1, 3, 2, 4)
(5, 0, 1, 3, 4, 2)
(5, 0, 1, 4, 2, 3)
(5, 0, 1, 4, 3, 2)
(5, 0, 2, 1, 3, 4)
(5, 0, 2, 1, 4, 3)
(5, 0, 2, 3, 1, 4)
(5, 0, 2, 3, 4, 1)
(5, 0, 2, 4, 1, 3)
(5, 0, 2, 4, 3, 1)
(5, 0, 3, 1, 2, 4)
(5, 0, 3, 1, 4, 2)
(5, 0, 3, 2, 1, 4)
(5, 0, 3, 2, 4, 1)
(5, 0, 3, 4, 1, 2)
(5, 0, 3, 4, 2, 1)
(5, 0, 4, 1, 2, 3)
(5, 0, 4, 1, 3, 2)
(5, 0, 4, 2, 1, 3)
(5, 0, 4, 2, 3, 1)
(5, 0, 4, 3, 1, 2)
(5, 0, 4, 3, 2, 1)
(5, 1, 0, 2, 3, 4)
(5, 1, 0, 2, 4, 3)
(5, 1, 0, 3, 2, 4)
(5, 1, 0, 3, 4, 2)
(5, 1, 0, 4, 2, 3)
(5, 1, 0, 4, 3, 2)
(5, 1, 2, 0, 3, 4)
(5, 1, 2, 0, 4, 3)
(5, 1, 2, 3, 0, 4)
(5, 1, 2, 3, 4, 0)
(5, 1, 2, 4, 0, 3)
(5, 1, 2, 4, 3, 0)
(5, 1, 3, 0, 2, 4)
(5, 1, 3, 0, 4, 2)
(5, 1, 3, 2, 0, 4)
(5, 1, 3, 2, 4, 0)
(5, 1, 3, 4, 0, 2)
(5, 1, 3, 4, 2, 0)
(5, 1, 4, 0, 2, 3)
(5, 1, 4, 0, 3, 2)
(5, 1, 4, 2, 0, 3)
(5, 1, 4, 2, 3, 0)
(5, 1, 4, 3, 0, 2)
(5, 1, 4, 3, 2, 0)
(5, 2, 0, 1, 3, 4)
(5, 2, 0, 1, 4, 3)
(5, 2, 0, 3, 1, 4)
(5, 2, 0, 3, 4, 1)
(5, 2, 0, 4, 1, 3)
(5, 2, 0, 4, 3, 1)
(5, 2, 1, 0, 3, 4)
(5, 2, 1, 0, 4, 3)
(5, 2, 1, 3, 0, 4)
(5, 2, 1, 3, 4, 0)
(5, 2, 1, 4, 0, 3)
(5, 2, 1, 4, 3, 0)
(5, 2, 3, 0, 1, 4)
(5, 2, 3, 0, 4, 1)
(5, 2, 3, 1, 0, 4)
(5, 2, 3, 1, 4, 0)
(5, 2, 3, 4, 0, 1)
(5, 2, 3, 4, 1, 0)
(5, 2, 4, 0, 1, 3)
(5, 2, 4, 0, 3, 1)
(5, 2, 4, 1, 0, 3)
(5, 2, 4, 1, 3, 0)
(5, 2, 4, 3, 0, 1)
(5, 2, 4, 3, 1, 0)
(5, 3, 0, 1, 2, 4)
(5, 3, 0, 1, 4, 2)
(5, 3, 0, 2, 1, 4)
(5, 3, 0, 2, 4, 1)
(5, 3, 0, 4, 1, 2)
(5, 3, 0, 4, 2, 1)
(5, 3, 1, 0, 2, 4)
(5, 3, 1, 0, 4, 2)
(5, 3, 1, 2, 0, 4)
(5, 3, 1, 2, 4, 0)
(5, 3, 1, 4, 0, 2)
(5, 3, 1, 4, 2, 0)
(5, 3, 2, 0, 1, 4)
(5, 3, 2, 0, 4, 1)
(5, 3, 2, 1, 0, 4)
(5, 3, 2, 1, 4, 0)
(5, 3, 2, 4, 0, 1)
(5, 3, 2, 4, 1, 0)
(5, 3, 4, 0, 1, 2)
(5, 3, 4, 0, 2, 1)
(5, 3, 4, 1, 0, 2)
(5, 3, 4, 1, 2, 0)
(5, 3, 4, 2, 0, 1)
(5, 3, 4, 2, 1, 0)
(5, 4, 0, 1, 2, 3)
(5, 4, 0, 1, 3, 2)
(5, 4, 0, 2, 1, 3)
(5, 4, 0, 2, 3, 1)
(5, 4, 0, 3, 1, 2)
(5, 4, 0, 3, 2, 1)
(5, 4, 1, 0, 2, 3)
(5, 4, 1, 0, 3, 2)
(5, 4, 1, 2, 0, 3)
(5, 4, 1, 2, 3, 0)
(5, 4, 1, 3, 0, 2)
(5, 4, 1, 3, 2, 0)
(5, 4, 2, 0, 1, 3)
(5, 4, 2, 0, 3, 1)
(5, 4, 2, 1, 0, 3)
(5, 4, 2, 1, 3, 0)
(5, 4, 2, 3, 0, 1)
(5, 4, 2, 3, 1, 0)
(5, 4, 3, 0, 1, 2)
(5, 4, 3, 0, 2, 1)
(5, 4, 3, 1, 0, 2)
(5, 4, 3, 1, 2, 0)
(5, 4, 3, 2, 0, 1)
(5, 4, 3, 2, 1, 0)
[c, omega_0, v]
(0, 1, 2)
(0, 2, 1)
(1, 0, 2)
(1, 2, 0)
(2, 0, 1)
(2, 1, 0)
[B, h, mom]
(0, 1, 2)
(0, 2, 1)
[B, mom, theta]
(0, 1, 2)
[T, c, h, kb, omega]
[F, r, theta]
(0, 1, 2)
[Ef, m, omega, omega_0, q]
[c, epsilon, q, r, v]
[epsilon, p_d, r, theta]
(0, 1, 2, 3)
(0, 1, 3, 2)
(0, 2, 1, 3)
(0, 2, 3, 1)
(0, 3, 1, 2)
(0, 3, 2, 1)
(1, 0, 2, 3)
(1, 0, 3, 2)
(1, 2, 0, 3)
(1, 2, 3, 0)
(1, 3, 0, 2)
(1, 3, 2, 0)
(2, 0, 1, 3)
(2, 0, 3, 1)
(2, 1, 0, 3)
(2, 1, 3, 0)
(2, 3, 0, 1)
(2, 3, 1, 0)
(3, 0, 1, 2)
(3, 0, 2, 1)
(3, 1, 0, 2)
(3, 1, 2, 0)
(3, 2, 0, 1)
(3, 2, 1, 0)
[B, Jz, g_, h, mom]
(0, 1, 2, 3, 4)
(0, 1, 2, 4, 3)
(0, 1, 3, 2, 4)
(0, 1, 3, 4, 2)
(0, 1, 4, 2, 3)
(0, 1, 4, 3, 2)
(0, 2, 1, 3, 4)
(0, 2, 1, 4, 3)
(0, 2, 3, 1, 4)
(0, 2, 3, 4, 1)
(0, 2, 4, 1, 3)
(0, 2, 4, 3, 1)
(0, 3, 1, 2, 4)
[g, m, z]
(0, 1, 2)
[G, m1, m2, r1, r2]
(0, 1, 2, 3, 4)
(0, 1, 2, 4, 3)
(0, 1, 3, 2, 4)
(0, 1, 3, 4, 2)
(0, 1, 4, 2, 3)
(0, 1, 4, 3, 2)
(0, 2, 1, 3, 4)
(0, 2, 1, 4, 3)
(0, 2, 3, 1, 4)
(0, 2, 3, 4, 1)
(0, 2, 4, 1, 3)
(0, 2, 4, 3, 1)
(0, 3, 1, 2, 4)
(0, 3, 1, 4, 2)
(0, 3, 2, 1, 4)
(0, 3, 2, 4, 1)
(0, 3, 4, 1, 2)
(0, 3, 4, 2, 1)
(0, 4, 1, 2, 3)
(0, 4, 1, 3, 2)
(0, 4, 2, 1, 3)
(0, 4, 2, 3, 1)
(0, 4, 3, 1, 2)
(0, 4, 3, 2, 1)
(1, 0, 2, 3, 4)
(1, 0, 2, 4, 3)
(1, 0, 3, 2, 4)
(1, 0, 3, 4, 2)
(1, 0, 4, 2, 3)
(1, 0, 4, 3, 2)
(1, 2, 0, 3, 4)
(1, 2, 0, 4, 3)
(1, 2, 3, 0, 4)
(1, 2, 3, 4, 0)
(1, 2, 4, 0, 3)
(1, 2, 4, 3, 0)
(1, 3, 0, 2, 4)
(1, 3, 0, 4, 2)
(1, 3, 2, 0, 4)
(1, 3, 2, 4, 0)
(1, 3, 4, 0, 2)
(1, 3, 4, 2, 0)
(1, 4, 0, 2, 3)
(1, 4, 0, 3, 2)
(1, 4, 2, 0, 3)
(1, 4, 2, 3, 0)
(1, 4, 3, 0, 2)
(1, 4, 3, 2, 0)
(2, 0, 1, 3, 4)
(2, 0, 1, 4, 3)
(2, 0, 3, 1, 4)
(2, 0, 3, 4, 1)
(2, 0, 4, 1, 3)
(2, 0, 4, 3, 1)
(2, 1, 0, 3, 4)
(2, 1, 0, 4, 3)
(2, 1, 3, 0, 4)
(2, 1, 3, 4, 0)
(2, 1, 4, 0, 3)
(2, 1, 4, 3, 0)
(2, 3, 0, 1, 4)
(2, 3, 0, 4, 1)
(2, 3, 1, 0, 4)
(2, 3, 1, 4, 0)
(2, 3, 4, 0, 1)
(2, 3, 4, 1, 0)
(2, 4, 0, 1, 3)
(2, 4, 0, 3, 1)
(2, 4, 1, 0, 3)
(2, 4, 1, 3, 0)
(2, 4, 3, 0, 1)
(2, 4, 3, 1, 0)
(3, 0, 1, 2, 4)
(3, 0, 1, 4, 2)
(3, 0, 2, 1, 4)
(3, 0, 2, 4, 1)
(3, 0, 4, 1, 2)
(3, 0, 4, 2, 1)
(3, 1, 0, 2, 4)
(3, 1, 0, 4, 2)
(3, 1, 2, 0, 4)
(3, 1, 2, 4, 0)
(3, 1, 4, 0, 2)
(3, 1, 4, 2, 0)
(3, 2, 0, 1, 4)
(3, 2, 0, 4, 1)
(3, 2, 1, 0, 4)
(3, 2, 1, 4, 0)
(3, 2, 4, 0, 1)
(3, 2, 4, 1, 0)
(3, 4, 0, 1, 2)
(3, 4, 0, 2, 1)
(3, 4, 1, 0, 2)
(3, 4, 1, 2, 0)
(3, 4, 2, 0, 1)
(3, 4, 2, 1, 0)
(4, 0, 1, 2, 3)
(4, 0, 1, 3, 2)
(4, 0, 2, 1, 3)
(4, 0, 2, 3, 1)
(4, 0, 3, 1, 2)
(4, 0, 3, 2, 1)
(4, 1, 0, 2, 3)
(4, 1, 0, 3, 2)
(4, 1, 2, 0, 3)
(4, 1, 2, 3, 0)
(4, 1, 3, 0, 2)
(4, 1, 3, 2, 0)
(4, 2, 0, 1, 3)
(4, 2, 0, 3, 1)
(4, 2, 1, 0, 3)
(4, 2, 1, 3, 0)
(4, 2, 3, 0, 1)
(4, 2, 3, 1, 0)
(4, 3, 0, 1, 2)
(4, 3, 0, 2, 1)
(4, 3, 1, 0, 2)
(4, 3, 1, 2, 0)
(4, 3, 2, 0, 1)
(4, 3, 2, 1, 0)
[c, m_0, v]
(0, 1, 2)
(0, 2, 1)
(1, 0, 2)
(1, 2, 0)
(2, 0, 1)
(2, 1, 0)
[Ef, q2]
(0, 1)
[Volt, d, mu_drift, q]
(0, 1, 2, 3)
(0, 1, 3, 2)
(0, 2, 1, 3)
(0, 2, 3, 1)
[Ef, p_d, theta]
(0, 1, 2)
(0, 2, 1)
(1, 0, 2)
(1, 2, 0)
(2, 0, 1)
(2, 1, 0)

In [43]:
df_merged[df_merged['equivalent']==True]

,Equation,loss,Predicted Equation,equivalent
Filename,,,,
III.15.27,2*pi*alpha/(d*n),0.000016,6.283166*x0/(x1*x2),True
III.7.38,4*pi*B*mom/h,0.003299,12.566449*x0*x1/x2,True
II.15.4,-B*mom*cos(theta),0.000043,-0.99999650001225*x0*x1*cos(x2),True
I.18.12,F*r*sin(theta),0.000057,x0*x1*sin(x2),True
II.34.29b,2*pi*B*Jz*g_*mom/h,0.091172,6.2831473*x0*x2*x3*x4/x1,True
I.14.3,g*m*z,0.001108,x0*x1*x2,True
I.12.5,Ef*q2,0.000107,x0*x1,True
I.43.16,Volt*mu_drift*q/d,0.000219,x0*x1*x2/x3,True

In [ ]:
df_merged.to_csv('llm_unguided_results_20_eqs')
# df_merged.to_csv('non_guided_results_20_eqs')
# score (pysr with defaults) = 46/97 (appx 47%) # took at most a minute to run
# score (pysr with added sqrt, sin, exp, cos) = 55/97 (appx 56%) ~ took about 30 minutes to run


# previous run: 9 correct equations predicted out of 20 (ran in 30 minutes) - LLM aided
# current run: 8 correct equations predicted out of 20 (ran in 7 minutes)

In [36]:
df_guided = pd.read_csv('llm_guided_results_97_eqs')
df_unguided = pd.read_csv('llm_unguided_results_97_eqs')
df_guided.set_index('Filename')
df_unguided.set_index('Filename')
df_guided.merge(df_unguided,on='Filename')[['Equation_x','Predicted Equation_x', 'Predicted Equation_y','equivalent_x','equivalent_y']]

,Equation_x,Predicted Equation_x,Predicted Equation_y,equivalent_x,equivalent_y
0,2*pi*alpha/(d*n),6.28323319849305*x0/(x1*x2),6.28323319849305*x0/(x1*x2),True,True
1,h*omega/(2*pi*(exp(h*omega/(2*pi*T*kb)) - 1)),x2*x3,x2*x3,False,False
2,m*x**2*(omega**2 + omega_0**2)/4,x0*x3**2*(x1 + x2 - 1.8324685),x0*x3**2*(x1 + x2 - 1.8324685),False,False
3,8*pi*Ef*p_d*sin(t*(omega - omega_0)/2)**2/(h*t...,4.42580905926945*x0*x1*exp(0.51191103*x2*cos(x...,4.42580905926945*x0*x1*exp(0.51191103*x2*cos(x...,False,False
4,omega_0*(1 + v/c)/sqrt(1 - v**2/c**2),x2*exp(x1/x0),x2*exp(x1/x0),False,False
...,...,...,...,...,...
92,m*r*v*sin(theta),x0*x1*x2*sin(x3),x0*x1*x2*sin(x3),True,True
93,n_0/(exp(B*mom/(T*kb)) + exp(-B*mom/(T*kb))),0.4727302*x0*sin(2.04129526460306*exp(-x3*x4/(...,0.4727302*x0*sin(2.04129526460306*exp(-x3*x4/(...,False,False
94,q/C,x0/x1,x0/x1,True,True
95,mom*n_rho*tanh(B*mom/(T*kb)),x0*(x1 - 0.7452803),x0*(x1 - 0.7452803),False,False
96,2*U*(1 - cos(d*k)),1.9999362*x0*sin(x1*x2 - 1.5708106) + 1.999936...,1.9999362*x0*sin(x1*x2 - 1.5708106) + 1.999936...,False,False